### ISSUE TITLE
Checkstyle-check crashes when there's no XML output to analyze

### ISSUE THREAD

**Issue by AlejandroRivera** [Redmart/sbt-checkstyle-plugin#3]
For example, create a new project with no tests files. 
Execute `sbt clean test:checkstyle-check`. 

Expected outcome: Success (no checkstyle violations found, build is successful)
Actual outcome:

```
Must specify files to process
usage: java com.puppycrawl.tools.checkstyle.Main [options] -c <config.xml>
            file...
 -c <arg>   The check configuration file to use.
 -f <arg>   Sets the output format. (plain|xml). Defaults to plain
 -o <arg>   Sets the output file. Defaults to stdout
 -p <arg>   Loads the properties file
 -v         Print product version and exit
[info] Will fail the build if errors are found in Checkstyle's XML report.
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1437)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1019)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:333)
        at scala.xml.factory.XMLLoader$class.loadXML(XMLLoader.scala:40)
        at scala.xml.XML$.loadXML(XML.scala:57)
        at scala.xml.factory.XMLLoader$class.loadFile(XMLLoader.scala:47)
        at scala.xml.XML$.loadFile(XML.scala:57)
        at com.etsy.sbt.Checkstyle$$anonfun$checkstyleCheckTask$1.apply(Checkstyle.scala:107)
        at com.etsy.sbt.Checkstyle$$anonfun$checkstyleCheckTask$1.apply(Checkstyle.scala:75)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (test:checkstyleCheck) org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
[error] Total time: 0 s, completed Dec 1, 2015 10:13:51 AM
```

**Comment by JosephEarl** [comment]
Something like the following in checkstyleCheckTask:

```scala
if (file(outputFile).exists) {
  val report = scala.xml.XML.loadFile(file(outputFile))
  ...
}
```

**Comment by AlejandroRivera** [comment]
Yup, this was an easy one. I probably spent more time creating this issue than would have spent fixing it haha.

Anyway, thanks for taking care of this as part of your PR: https://github.com/etsy/sbt-checkstyle-plugin/pull/10/
